config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "parties#index"

  resources :users, only: [:edit, :update]
  resources :parties, only: [:index, :new, :create] do
    resources :drinks, only: [:index, :create]
    namespace :api do
      resources :drinks, only: [:index], defaults: {format: 'json'}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :user
  belongs_to :party

  validates :name, presence: true
  validates :amount, presence: true, numericality: {only_integer: true}
  validates :content, presence: true, numericality: {less_than_or_equal_to: 100.0}

  def alcohol
    amount * content / 100 * 0.8
  end

end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :user
  has_many :drinks
  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :weight, presence: true
  validates :password, presence: true
  validates :email, presence: true
  has_many :parties
  has_many :drinks
end

app/controllers/api/drinks_controller.rb
class Api::DrinksController < ApplicationController

  def index
    party = Party.find(params[:party_id])
    @drinks = party.drinks.includes(:user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :weight])
  end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_party
  def index
    if current_user.id == @party.user_id
      @drink = Drink.new
      @drinks = @party.drinks.includes(:user)
      sum_alcohol(@drinks)
    else
      redirect_to root_path
    end
  end

  def create
    @drink = @party.drinks.new(drink_params)
    if @drink.save
      respond_to do |format|
        format.json
      end
    else
      @drinks = @party.drinks.includes(:user)
      render :index
    end
  end

  private
  def set_party
    @party = Party.find(params[:party_id])
  end

  def drink_params
    params.require(:drink).permit(:name, :amount, :content, :comment).merge(user_id: current_user.id)
  end

  def sum_alcohol(drinks)
    @sum_alcohol = 0
    drinks.each do |drink|
      @sum_alcohol += drink.alcohol
    end
    return @sum_alcohol
  end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
  end

  def new
    @party = Party.new
  end

  def create
    party = Party.new(party_params)
    if party.save
      redirect_to party_drinks_path(party.id)
    else
      @party = Party.new
      render :new
    end
  end

  private
  def party_params
    params.require(:party).permit(:name).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :weight, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drinks/_drink.html.haml
.drink
  .drink__content
    .drink__content--top
      = drink.name
    .drink__content--center
      = "飲酒量: #{drink.amount}ml 度数: #{drink.content}% アルコール量: #{drink.alcohol}g"
    .drink__content--bottom
      = drink.comment
  .drink__info
    = drink.created_at.strftime("%m/%d %H:%M")

app/views/drinks/_main_contents.html.haml
.main
  .top-contents
    .top-contents__content#timer
      .top-contents__content--up
        アルコールが分解されるまで
      .top-contents__content--down
        0時間0分0秒
    .top-contents__content#sum
      .top-contents__content--up#sum-text
        総アルコール量
      .top-contents__content--down#sum-alcohol{data: {sumalcohol: @sum_alcohol}}
        = "#{@sum_alcohol}g"

  .drink-list
    = render partial: "drinks/drink", collection: @drinks

  = form_with(model: [@party, @drink], local: true, class: "footer", id: "new-drink") do |f|
    .input-form
      .input-form__top
        .form-content
          .form-info
            お酒
          = f.text_field :name, class: "form-text"
        .form-content
          .form-info
            度数
          = f.text_field :content, placeholder: "0.0 ~ 100,0 %", class: "form-text"
        .form-content
          .form-info
            飲酒量
          = f.text_field :amount, placeholder: "0 ~ 1000 ml", class: "form-text"
      .input-form__bottom
        .input-form__bottom--comment
          コメント
        = f.text_field :comment, class: "form-text"
    .send-btn
      %label
        = icon('fas', 'beer', class: "send-btn__icon")
        = f.submit '飲んだ!', class: "send-btn__submit"

app/views/drinks/index.html.haml
.wrapper
  = render "shared/side_bar"
  = render "main_contents"

app/views/layouts/_header.html.haml
.header
  = link_to root_path, class: "title" do
    TOO DRUNK TO WORK
  .user-box
    - if user_signed_in?
      = link_to edit_user_registration_path(current_user), class: "user-box__btn" do
        = current_user.name
      = link_to destroy_user_session_path, method: :delete, class: "user-box__btn" do
        ログアウト
    - else
      = link_to new_user_session_path, class: "user-box__btn" do
        ログイン
      = link_to new_user_registration_path, class: "user-box__btn" do
        新規登録

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TooDrunkToWork
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render "layouts/header"
    = yield

app/views/parties/index.html.haml
.wrapper
  = render "shared/side_bar"

app/views/parties/new.html.haml
.wrapper
  = render "shared/side_bar"
  .main
    = form_with model: @party, local: true, class: "party-form" do |f|
      = f.text_field :name, class: "party-form__input", placeholder: "飲み会名を入力してください"
      = f.submit "参加する", class: "party-form__action-btn"

app/views/shared/_side_bar.html.haml
.side-bar
  .party-list
    - current_user.parties.each do |party|
      .party-list__box
        = link_to party_drinks_path(party.id), class: "party" do
          .party__name
            = party.name
          .party__date
            = party.created_at.strftime("%Y/%m/%d")

  = link_to new_party_path, class: "new-party" do
    飲み会を追加
    = icon('fas', 'glass-cheers', class: "new-party__icon")